version: '3.8'
services:
  searxng:
    image: searxng/searxng
    container_name: my-searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=my-instance
    restart: unless-stopped
